version: "3.8"

services:
    # Controller 1
    controller-1:
        image: confluentinc/cp-kafka:latest
        container_name: controller-1
        hostname: controller-1
        environment:
            # Core Kafka Settings
            KAFKA_ENABLE_KRAFT: "yes" #? Enables KRaft mode (ZooKeeper-less Kafka)
            KAFKA_NODE_ID: "1" #? Unique ID for this controller node
            KAFKA_PROCESS_ROLES: "controller" #? Defines this node as a controller only
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw==" #? Unique ID for the Kafka cluster
            # Listener Configuration
            KAFKA_LISTENERS: "CONTROLLER://controller-1:19093" #? Listener for quorum communication
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #? Name of the controller listener
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT" #? Maps CONTROLLER listener to plaintext protocol
            # Quorum Configuration
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093" #? List of controllers for quorum voting
            # Logging and Storage
            KAFKA_LOG_DIRS: "/var/lib/kafka/data" #? Directory for storing Kafka logs
            KAFKA_LOG_RETENTION_HOURS: "168" #? Retains logs for 7 days (168 hours)
            # Resource Settings
            KAFKA_HEAP_OPTS: "-Xms2g -Xmx2g" #? Sets Java heap size to 2GB min/max
        volumes:
            - controller-1-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "4g"
        networks:
            - kafka-net
        restart: unless-stopped

    # Controller 2
    controller-2:
        image: confluentinc/cp-kafka:latest
        container_name: controller-2
        hostname: controller-2
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_NODE_ID: "2"
            KAFKA_PROCESS_ROLES: "controller"
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw=="
            KAFKA_LISTENERS: "CONTROLLER://controller-2:19093"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093"
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
            KAFKA_LOG_RETENTION_HOURS: "168"
            KAFKA_HEAP_OPTS: "-Xms2g -Xmx2g"
        volumes:
            - controller-2-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "4g"
        networks:
            - kafka-net
        restart: unless-stopped

    # Controller 3
    controller-3:
        image: confluentinc/cp-kafka:latest
        container_name: controller-3
        hostname: controller-3
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_NODE_ID: "3"
            KAFKA_PROCESS_ROLES: "controller"
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw=="
            KAFKA_LISTENERS: "CONTROLLER://controller-3:19093"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093"
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
            KAFKA_LOG_RETENTION_HOURS: "168"
            KAFKA_HEAP_OPTS: "-Xms2g -Xmx2g"
        volumes:
            - controller-3-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "4g"
        networks:
            - kafka-net
        restart: unless-stopped

    # Broker 1
    kafka-broker-1:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-broker-1
        hostname: kafka-broker-1
        ports:
            - "9092:9092"
        environment:
            # Core Kafka Settings
            KAFKA_ENABLE_KRAFT: "yes" #? Enables KRaft mode for this broker
            KAFKA_NODE_ID: "101" #? Unique ID for this broker node
            KAFKA_PROCESS_ROLES: "broker" #? Defines this node as a broker only
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw==" #? Unique ID for the Kafka cluster
            # Listener Configuration
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL_DOCKER:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT" #? Maps listener names to protocols
            KAFKA_LISTENERS: "INTERNAL://kafka-broker-1:19092,EXTERNAL_DOCKER://kafka-broker-1:29092,EXTERNAL_HOST://0.0.0.0:9092" #? Defines listeners for inter-broker and client communication
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-1:19092,EXTERNAL_DOCKER://kafka-broker-1:29092,EXTERNAL_HOST://localhost:9092" #? Advertises listeners for external access
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL" #? Specifies INTERNAL listener for broker-to-broker communication
            # Controller Communication
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093" #? List of controllers for metadata
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #? Name of the listener to connect to controllers
            # Replication Settings
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3" #? Replication factor for offsets topic
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3" #? Replication factor for transaction logs
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2" #? Minimum in-sync replicas for transaction logs
            KAFKA_DEFAULT_REPLICATION_FACTOR: "3" #? Default replication factor for new topics
            KAFKA_NUM_PARTITIONS: "6" #? Number of partitions for new topics
            KAFKA_MIN_INSYNC_REPLICAS: "2" #? Minimum in-sync replicas for writes
            KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false" #? Ensures consistency over availability
            # Consumer Group Settings
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0" #? Delay before consumer group rebalancing
            # Logging and Storage
            KAFKA_LOG_DIRS: "/var/lib/kafka/data" #? Directory for storing Kafka logs
            KAFKA_LOG_RETENTION_HOURS: "168" #? Retains logs for 7 days (168 hours)
            KAFKA_LOG_SEGMENT_BYTES: "1073741824" #? Log segment size set to 1GB
            KAFKA_LOG_RETENTION_BYTES: "-1" #? No size-based log retention limit
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" #? Prevents automatic topic creation. In production, it is not recommended to automatically create topics as it risks unintended topic creation
            # Resource Settings
            KAFKA_HEAP_OPTS: "-Xms4g -Xmx4g" #? Sets Java heap size to 4GB min/max
        volumes:
            - kafka-broker-1-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: "8g"
        restart: unless-stopped
        networks:
            - kafka-net
        depends_on:
            - controller-1
            - controller-2
            - controller-3

    # Broker 2
    kafka-broker-2:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-broker-2
        hostname: kafka-broker-2
        ports:
            - "9093:9092"
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_NODE_ID: "102"
            KAFKA_PROCESS_ROLES: "broker"
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw=="
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL_DOCKER:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka-broker-2:19092,EXTERNAL_DOCKER://kafka-broker-2:29092,EXTERNAL_HOST://0.0.0.0:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-2:19092,EXTERNAL_DOCKER://kafka-broker-2:29092,EXTERNAL_HOST://localhost:9093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
            KAFKA_DEFAULT_REPLICATION_FACTOR: "3"
            KAFKA_NUM_PARTITIONS: "6"
            KAFKA_MIN_INSYNC_REPLICAS: "2"
            KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
            KAFKA_LOG_RETENTION_HOURS: "168"
            KAFKA_LOG_SEGMENT_BYTES: "1073741824"
            KAFKA_LOG_RETENTION_BYTES: "-1"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_HEAP_OPTS: "-Xms4g -Xmx4g"
        volumes:
            - kafka-broker-2-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: "8g"
        networks:
            - kafka-net
        restart: unless-stopped
        depends_on:
            - controller-1
            - controller-2
            - controller-3

    # Broker 3
    kafka-broker-3:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-broker-3
        hostname: kafka-broker-3
        ports:
            - "9094:9092"
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_NODE_ID: "103"
            KAFKA_PROCESS_ROLES: "broker"
            CLUSTER_ID: "4L8ckgmVQHWKkaFx1nP2iw=="
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL_DOCKER:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka-broker-3:19092,EXTERNAL_DOCKER://kafka-broker-3:29092,EXTERNAL_HOST://0.0.0.0:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-3:19092,EXTERNAL_DOCKER://kafka-broker-3:29092,EXTERNAL_HOST://localhost:9094"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:19093,2@controller-2:19093,3@controller-3:19093"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
            KAFKA_DEFAULT_REPLICATION_FACTOR: "3"
            KAFKA_NUM_PARTITIONS: "6"
            KAFKA_MIN_INSYNC_REPLICAS: "2"
            KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
            KAFKA_LOG_RETENTION_HOURS: "168"
            KAFKA_LOG_SEGMENT_BYTES: "1073741824"
            KAFKA_LOG_RETENTION_BYTES: "-1"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_HEAP_OPTS: "-Xms4g -Xmx4g"
        volumes:
            - kafka-broker-3-data:/var/lib/kafka/data
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: "8g"
        networks:
            - kafka-net
        restart: unless-stopped
        depends_on:
            - controller-1
            - controller-2
            - controller-3

    # Kafka UI
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8080:8080"
        environment:
            # Kafka Cluster Configuration
            KAFKA_CLUSTERS_0_NAME: "local"
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:29092,kafka-broker-2:29092,kafka-broker-3:29092"
        networks:
            - kafka-net
        depends_on:
            - kafka-broker-1
            - kafka-broker-2
            - kafka-broker-3

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80" # Expose Nginx on port 80
        volumes:
            # - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx config
            - /mnt/d/OCodes/kafka/nginx.conf:/etc/nginx/nginx.conf # Mount custom Nginx config
        networks:
            - kafka-net
        restart: unless-stopped

volumes:
    controller-1-data:
    controller-2-data:
    controller-3-data:
    kafka-broker-1-data:
    kafka-broker-2-data:
    kafka-broker-3-data:

networks:
    kafka-net:
        driver: bridge
